when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error

when@prod:
    framework:
        error_controller: App\Controller\ErrorController::show
